language: objective-c
osx_image: xcode8.2
env:
  global:
    - SCAN_SKIP_BUILD=1
    - SCAN_WORKSPACE="Example/VOKMockUrlProtocol.xcworkspace"
  matrix:
    # Define the details for each test suite that should be run
    - SCAN_SCHEME="VOKMockUrlProtocol"         SCAN_SDK="iphonesimulator"
    - SCAN_SCHEME="VOKMockUrlProtocol-tvOS"    SCAN_SDK="appletvsimulator"
    - SCAN_SCHEME="VOKMockUrlProtocol-OSX"     SCAN_SDK="macosx"
script: bundle exec scan
after_script:
  - bundle exec pod lib lint
git:
  depth: 10000  # For the auto-incrementing build number script to work, we need to clone with a basically-infinite depth.
cache:
  - bundler  # After main-repo builds, save the "bundler" (local Ruby gems) stuff to cache for future builds.
